doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        types:
            account_id: App\Account\Infrastructure\DoctrineMappings\AccountIdType
            user_id: App\Dashboard\User\Infrastructure\DoctrineMappings\UserIdType
            board_id: App\Board\Infrastructure\DoctrineMappings\BoardIdType
            column_id: App\Board\Infrastructure\DoctrineMappings\ColumnIdType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          Board:
              type: xml
              is_bundle: false
              dir: '%kernel.project_dir%/src/Dashboard/Board/Infrastructure/DoctrineMappings'
              prefix: 'App\Dashboard\Board\Domain\Entity'
              alias: Board

          Account:
              type: xml
              is_bundle: false
              dir: '%kernel.project_dir%/src/Account/Infrastructure/DoctrineMappings'
              prefix: 'App\Account\Domain\Entity'
              alias: Account

          User:
              type: xml
              is_bundle: false
              dir: '%kernel.project_dir%/src/Dashboard/User/Infrastructure/DoctrineMappings'
              prefix: 'App\Dashboard\User\Domain\Entity'
              alias: User

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
