version: "3.8"
services:
  database:
    container_name: kanban_database
    image: arm64v8/mariadb:10.9.3
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - '3333:3306'
    networks:
      - kanban

  php:
    container_name: kanban_php
    restart: on-failure
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/kanban
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - database
    networks:
      - kanban

  phpmyadmin:
    container_name: kanban_pma
    image: arm64v8/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: on-failure
    ports:
      - '8081:80'
    networks:
      - kanban

  nginx:
    container_name: kanban_nginx
    image: arm64v8/nginx
    restart: on-failure
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/kanban
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - kanban

networks:
  kanban:
    driver: bridge
