board_controller:
    resource:
        path: ../src/Dashboard/Board/Application/Controller/
        namespace: App\Dashboard\Board\Application\Controller
    type: attribute

account_controller:
    resource:
        path: ../src/Account/Application/Controller/
        namespace: App\Account\Application\Controller
    type: attribute

api_login_check:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh

api_token_invalidate:
    path: /api/token/invalidate